//! Real OpenAI DALL-E Image Generation client.
//!
//! Implements `POST /v1/images/generations` for DALL-E 2 and DALL-E 3 image generation.

use serde::{Deserialize, Serialize};
use serde_json::json;
use std::time::Duration;

use crate::http::{
    HttpClient, map_reqwest_error, map_response_error, parse_json, retry_after_from_headers,
};
use ai_errors::AiError;

/// An image object generated by DALL-E.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageObject {
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub b64_json: Option<String>,
    #[serde(default)]
    pub revised_prompt: Option<String>,
}

/// Response payload from DALL-E image generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageGenerationResponse {
    pub created: i64,
    pub data: Vec<ImageObject>,
}

/// Client for OpenAI DALL-E image endpoints.
#[derive(Debug, Clone)]
pub struct OpenAiImageClient {
    api_key: String,
    base_url: String,
    http: HttpClient,
    timeout: Duration,
}

impl OpenAiImageClient {
    pub fn new(api_key: impl Into<String>, base_url: impl Into<String>) -> Result<Self, AiError> {
        let http = HttpClient::new()?;
        Ok(Self {
            api_key: api_key.into(),
            base_url: base_url.into(),
            http,
            timeout: Duration::from_secs(60),
        })
    }

    fn url(&self, path: &str) -> String {
        format!(
            "{}/{}",
            self.base_url.trim_end_matches('/'),
            path.trim_start_matches('/')
        )
    }

    /// Generates images from a text prompt (`POST /v1/images/generations`).
    pub async fn generate_image(
        &self,
        prompt: &str,
        model: Option<&str>,
        n: Option<u32>,
        size: Option<&str>,
        response_format: Option<&str>,
    ) -> Result<ImageGenerationResponse, AiError> {
        let mut payload = json!({ "prompt": prompt });
        if let Some(m) = model {
            payload["model"] = json!(m);
        }
        if let Some(num) = n {
            payload["n"] = json!(num);
        }
        if let Some(s) = size {
            payload["size"] = json!(s);
        }
        if let Some(fmt) = response_format {
            payload["response_format"] = json!(fmt);
        }

        let response = tokio::time::timeout(
            self.timeout,
            self.http
                .inner()
                .post(self.url("/v1/images/generations"))
                .bearer_auth(&self.api_key)
                .json(&payload)
                .send(),
        )
        .await
        .map_err(|_| {
            AiError::Timeout(ai_errors::TimeoutError::new("image.generate", self.timeout))
        })?
        .map_err(|e| map_reqwest_error("image.generate", e))?;

        let status = response.status();
        let retry_after = retry_after_from_headers(response.headers());
        let bytes = response
            .bytes()
            .await
            .map_err(|e| map_reqwest_error("image.generate", e))?
            .to_vec();

        if !status.is_success() {
            return Err(map_response_error("openai", status, retry_after, &bytes).await);
        }

        parse_json("image.generate", &bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn image_generation_response_deserializes() {
        let raw = r#"{
            "created": 1700000000,
            "data": [
                {"url": "https://example.com/image.png", "revised_prompt": "A cute cat"}
            ]
        }"#;
        let res: ImageGenerationResponse = serde_json::from_str(raw).unwrap();
        assert_eq!(res.created, 1700000000);
        assert_eq!(res.data.len(), 1);
        assert_eq!(
            res.data[0].url.as_deref(),
            Some("https://example.com/image.png")
        );
    }
}
